float:
  any:
  - base_args: ['@metric']
    constructor: RabitqMstg
    disabled: false
    docker_tag: ann-benchmarks-rabitq-mstg
    module: ann_benchmarks.algorithms.rabitq-mstg
    name: rabitq-mstg
    run_groups:
      gist-full:
        arg_groups:
        - max_posting_size: 256
          branching_factor: 4
          balance_weight: 0.0
          rabitq_bits: 5
          hnsw_m: 24
        query_args:
        - - ef_search: 100
          - ef_search: 200
