float:
  any:
  - base_args: ['@metric']
    constructor: RabitqIvf
    disabled: false
    docker_tag: ann-benchmarks-rabitq-ivf
    module: ann_benchmarks.algorithms.rabitq-ivf
    name: rabitq-ivf
    run_groups:
      gist-full:
        arg_groups: [{"nlist": 256, "total_bits": 7, "faster_config": true}]
        query_args: [[{"nprobe": 10}, {"nprobe": 50}]]
      # nlist_512:
      #   arg_groups: [{"nlist": 512, "total_bits": 7, "faster_config": true}]
      #   query_args: [[{"nprobe": 1}, {"nprobe": 5}, {"nprobe": 10}, {"nprobe": 50}, {"nprobe": 100}, {"nprobe": 200}]]
      # nlist_1024:
      #   arg_groups: [{"nlist": 1024, "total_bits": 7, "faster_config": true}]
      #   query_args: [[{"nprobe": 1}, {"nprobe": 5}, {"nprobe": 10}, {"nprobe": 50}, {"nprobe": 100}, {"nprobe": 200}]]
      # nlist_2048:
      #   arg_groups: [{"nlist": 2048, "total_bits": 7, "faster_config": true}]
      #   query_args: [[{"nprobe": 1}, {"nprobe": 5}, {"nprobe": 10}, {"nprobe": 50}, {"nprobe": 100}, {"nprobe": 200}]]
      # nlist_4096:
      #   arg_groups: [{"nlist": 4096, "total_bits": 7, "faster_config": true}]
      #   query_args: [[{"nprobe": 1}, {"nprobe": 5}, {"nprobe": 10}, {"nprobe": 50}, {"nprobe": 100}, {"nprobe": 200}, {"nprobe": 500}]]
